# -*- coding: utf-8 -*-
"""suc_udocker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EkRGSpR6irRZhDBiXEotc8Q7ApUSwQ3
"""





!curl -fsSL https://get.docker.com | sh

!docker

!sudo docker run --rm hello-world

!pip install udocker

!udocker install

# Commented out IPython magic to ensure Python compatibility.
# %env UDOCKER_ALLOW_ROOT=1

!udocker install

# Commented out IPython magic to ensure Python compatibility.
# %env UDOCKER_ALLOW_ROOT=1 & udocker install

!udocker --allow-root -h

!UDOCKER_ALLOW_ROOT=1 udocker install



!udocker --allow-root install

!udocker --allow-root run hello-world

!pip install udocker

"""Model
Thinking Thoughts

Expand to view model thoughts
chevron_right

ممتاز! بما أن hello-world اشتغلت، فهذا يعني أن محرك udocker جاهز تماماً.

بما أنك في Google Colab، الهدف غالباً هو تشغيل أكواد بايثون أو ذكاء اصطناعي. إليك الأكواد التالية لتبدأ العمل الجاد (انسخها وجربها):
1. تجربة بايثون داخل كونتينر (بدون GPU)

بدلاً من hello-world، دعنا نشغل نظام لينكس مصغر بداخله بايثون:
code Bash

# تحميل وتشغيل بايثون مباشرة وطباعة إصدارها
!udocker --allow-root run python:3.9-slim python --version

2. تشغيل الذكاء الاصطناعي مع GPU (الأهم) 🔥

هذه هي الخطوة الاحترافية. سنقوم بتحميل صورة PyTorch، ونضبط إعدادات NVIDIA لكي ترى الحاوية كرت الشاشة الخاص بجوجل كولاب.

نفذ هذه الأوامر في خلية جديدة بالترتيب:
code Bash

# 1. سحب صورة PyTorch (حجمها كبير قليلاً)
!udocker --allow-root pull pytorch/pytorch:latest

# 2. إنشاء الحاوية وتسميتها "my_ai" (بدون تشغيلها بعد)
!udocker --allow-root create --name=my_ai pytorch/pytorch:latest

# 3. ⚠️ الخطوة السحرية: نسخ تعريفات كرت الشاشة لداخل الحاوية
!udocker --allow-root setup --nvidia my_ai

# 4. تشغيل اختبار للتأكد أن الكرت يعمل
!udocker --allow-root run my_ai python -c "import torch; print('GPU Name:', torch.cuda.get_device_name(0))"

إذا طبع لك اسم الكرت (مثلاً Tesla T4)، فأنت نجحت في تشغيل Docker مع GPU داخل Colab!
3. كيف تصل لملفاتك داخل الكونتينر؟

إذا كان لديك كود أو داتا (Data) في ملفات Colab وتريد للكونتينر أن يراها، استخدم خيار --volume.

مثال:
code Bash

# هذا الأمر يجعل المجلد الحالي (.) في كولاب ظاهراً داخل الكونتينر في مسار /data
!udocker --allow-root run --volume=$(pwd):/data my_ai ls /data

info Google AI models may make mistakes, so double-check outputs.
Use Arrow Up and Arrow Down to select a turn, Enter to jump to it, and Escape to return to the chat.
google Grounding with Google Search

"""

!udocker --allow-root run --volume=$(pwd):/data my_ai ls /data

/content/sample_data

!udocker --allow-root run --volume=$(pwd):/sample_data my_ai ls /sample_data

# Commented out IPython magic to ensure Python compatibility.
# %cd /root/.udocker

!ls

!udocker --allow-root run --volume=$(pwd):/bin my_ai ls /bin

!udocker --allow-root pull python:3.9-slim

!udocker --allow-root create --name=my_lab python:3.9-slim

# تثبيت مكتبة numpy داخل الحاوية
!udocker --allow-root run my_lab pip install numpy

# تشغيل كود بايثون داخل الحاوية
!udocker --allow-root run my_lab python -c "import numpy; print('Numpy Version inside container:', numpy.__version__)"

!udocker --allow-root run my_lab sh -c "pip install pandas && python -c 'import pandas; print(pandas.__version__)'"

!udocker --allow-root run my_lab python --version

!udocker --allow-root run my_lab pip show numpy

!udocker --allow-root run my_lab python -c "import numpy; print(numpy.__version__)"

!udocker --allow-root run my_lab pip list





"""ممتاز! بما أن hello-world اشتغلت، فهذا يعني أن محرك udocker جاهز تماماً.

بما أنك في Google Colab، الهدف غالباً هو تشغيل أكواد بايثون أو ذكاء اصطناعي. إليك الأكواد التالية لتبدأ العمل الجاد (انسخها وجربها):
1. تجربة بايثون داخل كونتينر (بدون GPU)

بدلاً من hello-world، دعنا نشغل نظام لينكس مصغر بداخله بايثون:
code Bash

# تحميل وتشغيل بايثون مباشرة وطباعة إصدارها
!udocker --allow-root run python:3.9-slim python --version

2. تشغيل الذكاء الاصطناعي مع GPU (الأهم) 🔥

هذه هي الخطوة الاحترافية. سنقوم بتحميل صورة PyTorch، ونضبط إعدادات NVIDIA لكي ترى الحاوية كرت الشاشة الخاص بجوجل كولاب.

نفذ هذه الأوامر في خلية جديدة بالترتيب:
code Bash

# 1. سحب صورة PyTorch (حجمها كبير قليلاً)
!udocker --allow-root pull pytorch/pytorch:latest

# 2. إنشاء الحاوية وتسميتها "my_ai" (بدون تشغيلها بعد)
!udocker --allow-root create --name=my_ai pytorch/pytorch:latest

# 3. ⚠️ الخطوة السحرية: نسخ تعريفات كرت الشاشة لداخل الحاوية
!udocker --allow-root setup --nvidia my_ai

# 4. تشغيل اختبار للتأكد أن الكرت يعمل
!udocker --allow-root run my_ai python -c "import torch; print('GPU Name:', torch.cuda.get_device_name(0))"

إذا طبع لك اسم الكرت (مثلاً Tesla T4)، فأنت نجحت في تشغيل Docker مع GPU داخل Colab!
3. كيف تصل لملفاتك داخل الكونتينر؟

إذا كان لديك كود أو داتا (Data) في ملفات Colab وتريد للكونتينر أن يراها، استخدم خيار --volume.

مثال:
code Bash

# هذا الأمر يجعل المجلد الحالي (.) في كولاب ظاهراً داخل الكونتينر في مسار /data
!udocker --allow-root run --volume=$(pwd):/data my_ai ls /data

Model
Thinking Thoughts

Expand to view model thoughts
chevron_right

طلب ممتاز! بما أنك تعمل على المعالج (CPU) وتريد شيئاً خفيفاً وسريعاً للتجارب، أفضل خيار لك هو نسخة Python Slim.

حجمها صغير جداً (حوالي 40-50 ميجابايت) مقارنة بـ Ubuntu الكاملة، وتأتي مع بايثون جاهز.

إليك الخطوات لإنشاء الحاوية، الدخول إليها، وتثبيت مكتبة (مثلاً requests) وتجربتها، كل هذا باستخدام udocker في Colab:
1. سحب الصورة وإنشاء الحاوية

ضع هذا الكود في خلية وشغله مرة واحدة:
code Bash

# سحب صورة خفيفة جداً (Python Slim)
!udocker --allow-root pull python:3.9-slim

# إنشاء الحاوية وتسميتها "my_lab"
# (نستخدم create لنحفظ التغييرات التي سنقوم بها لاحقاً)
!udocker --allow-root create --name=my_lab python:3.9-slim

2. تثبيت المكتبة داخل الحاوية

الآن سنقوم بتشغيل الحاوية لتثبيت مكتبة (مثلاً numpy أو requests).
لاحظ أننا نستخدم اسم الحاوية my_lab وليس اسم الصورة.
code Bash

# تثبيت مكتبة numpy داخل الحاوية
!udocker --allow-root run my_lab pip install numpy

3. تجربة المكتبة (اختبار التثبيت)

الآن سنشغل الحاوية مرة أخرى لتشغيل كود بايثون يستخدم المكتبة التي ثبتناها للتو.
code Bash

# تشغيل كود بايثون داخل الحاوية
!udocker --allow-root run my_lab python -c "import numpy; print('Numpy Version inside container:', numpy.__version__)"

💡 ملاحظة مهمة جداً (كيف تعمل Colab مع التفاعلية):

في Google Colab، لا يمكنك "الدخول" إلى الشاشة السوداء (Shell) والبقاء فيها للكتابة سطراً بسطر كما في جهازك الشخصي (لأن Colab يفصل الاتصال بعد انتهاء تنفيذ الخلية).

لذلك، الطريقة التي كتبتها لك بالأعلى (تثبيت في خلية، ثم تشغيل في خلية أخرى) هي الطريقة الصحيحة، لأن udocker يحفظ التغييرات داخل المجلد my_lab، فعندما تشغل الخلية التالية، ستجد المكتبة مثبتة وجاهزة.

إذا كنت تريد تشغيل عدة أوامر معاً في سطر واحد، يمكنك فعل ذلك هكذا:
code Bash

!udocker --allow-root run my_lab sh -c "pip install pandas && python -c 'import pandas; print(pandas.__version__)'"

Model
Thinking Thoughts

Expand to view model thoughts
chevron_right

لمعرفة الإصدارات داخل الكونتينر (الذي سميناه my_lab سابقاً)، نستخدم الأمر run متبوعاً بأمر الاستعلام.

إليك الأوامر جاهزة للنسخ واللصق في كولاب:
1. لمعرفة إصدار بايثون (Python Version)
code Bash

!udocker --allow-root run my_lab python --version

2. لمعرفة إصدار مكتبة معينة (طريقة pip)

هذه الطريقة تعرض تفاصيل المكتبة (الإصدار، الموقع، الخ). استبدل numpy باسم المكتبة التي تريدها.
code Bash

!udocker --allow-root run my_lab pip show numpy

3. لمعرفة إصدار المكتبة (طريقة الكود - الأدق)

هذه الطريقة أفضل لأنها تتأكد أن المكتبة تعمل فعلاً وتقوم بطباعة رقم الإصدار فقط.
code Bash

!udocker --allow-root run my_lab python -c "import numpy; print(numpy.__version__)"

4. عرض كل المكتبات المثبتة

إذا كنت تريد قائمة بكل شيء موجود داخل الكونتينر:
code Bash

!udocker --allow-root run my_lab pip list

ملاحظة مهمة: تأكد دائماً من استخدام اسم الكونتينر (my_lab) وليس اسم الصورة (python:3.9-slim)، لأنك إذا استخدمت اسم الصورة، سيفتح كونتينر جديداً فارغاً ولن يجد المكتبات التي ثبتها سابقاً.
Model
Thinking Thoughts

Expand to view model thoughts
chevron_right

نعم، هذه الفكرة ممتازة وعملية جداً، خاصة في بيئات مثل Google Colab أو عند الرغبة في دمج كل شيء في مكان واحد.

بما أنك تستخدم udocker (بناءً على سياق حديثنا السابق)، فالأمر يتطلب "حيلة" بسيطة لأن الحاوية لا تحتوي على مدير خدمات (Systemd) لتشغيل أولاما في الخلفية تلقائياً.

إليك الخطوات الكاملة لتثبيت Ollama داخل حاوية AutoRAG، وتشغيل الخادم، وتحميل النماذج، ثم ربطها بـ AutoRAG.
الخطوة 1: الدخول إلى الحاوية وتثبيت Ollama

افترض أنك أنشأت الحاوية واسمها autorag_container. سنقوم بتنفيذ سلسلة أوامر لتثبيت أولاما.

انسخ هذا الكود في Colab:
code Bash

# 1. تحديث الحزم وتثبيت curl (أولاما يحتاجه)
!udocker --allow-root run autorag_container apt-get update && apt-get install -y curl

# 2. تحميل وتثبيت أولاما (يدوياً لأن سكريبت التثبيت التلقائي قد يفشل في udocker)
!udocker --allow-root run autorag_container bash -c "curl -L https://ollama.com/download/ollama-linux-amd64 -o /usr/bin/ollama && chmod +x /usr/bin/ollama"

الخطوة 2: تشغيل الخادم وتحميل الموديل (الخدعة هنا) 🔥

بما أننا في بيئة لا تدعم تشغيل الخدمات في الخلفية بشكل دائم، يجب علينا تشغيل خادم أولاما (ollama serve) وفي نفس السطر (في الخلفية) نطلب منه تحميل الموديل.

سنقوم بعمل سكربت صغير (setup_ollama.sh) داخل الحاوية ونشغله:
code Bash

# إنشاء سكريبت داخل الحاوية يقوم بالمهمة
!udocker --allow-root run autorag_container bash -c 'cat <<EOF > start_ollama.sh
#!/bin/bash
# تشغيل خادم أولاما في الخلفية
ollama serve &

# الانتظار قليلاً حتى يعمل الخادم
echo "Waiting for Ollama to start..."
sleep 5

# تحميل الموديل (مثلاً mistral أو llama3)
echo "Pulling Model..."
ollama pull mistral

# إبقاء السكريبت يعمل (اختياري حسب حاجتك) أو الخروج
echo "Model Pulled Successfully!"
EOF
chmod +x start_ollama.sh'

الآن، شغل هذا السكريبت لمرة واحدة ليقوم بالتحميل:
code Bash

!udocker --allow-root run autorag_container ./start_ollama.sh

الخطوة 3: كيف تجعل AutoRAG يرى Ollama؟

الآن الموديل موجود داخل الحاوية. عند تشغيل AutoRAG، يجب أن تتأكد من شيئين:

    تشغيل خادم أولاما قبل تشغيل AutoRAG:
    في كل مرة تريد تشغيل AutoRAG، يجب أن يكون الأمر كالتالي (في سطر واحد):
    code Bash

    !udocker --allow-root run autorag_container bash -c "ollama serve & python your_autorag_script.py"

    (لاحظ علامة & التي تجعل أولاما يعمل في الخلفية بينما يعمل سكريبت بايثون في الأمام).

    إعدادات AutoRAG (ملف YAML):
    داخل ملف إعدادات AutoRAG (عادة config.yaml)، يجب أن تختار نوع الـ LLM ليكون ollama وتحدد الرابط والاسم.

    مثال لإعداد الـ Config:
    code Yaml

    node_lines:
    - node_line_name: retrieve_node_line
      nodes:
        - node_type: retrieval
          strategy:
            metrics: [retrieval_f1, retrieval_recall]
          top_k: 3
          modules:
            - module_type: bm25
    - node_line_name: post_retrieve_node_line
      nodes:
        - node_type: generator
          strategy:
            metrics: [bleu, rouge, meteor]
          modules:
            - module_type: llama_index_llm
              llm: ollama
              model: mistral  # نفس الاسم الذي حملته
              base_url: http://localhost:11434  # الرابط الداخلي
              temperature: 0.1

ملخص سريع لما ستفعله:

    تثبت curl و ollama داخل الحاوية.

    تشغل ollama serve & ثم ollama pull model.

    عند تشغيل AutoRAG، تدمج أمر التشغيل ليكون: ollama serve & autorag run ....

بهذه الطريقة، الحاوية تصبح "مكتفية ذاتياً" (Self-contained)، بداخلها الكود والذكاء الاصطناعي معاً.
info Google AI models may make mistakes, so double-check outputs.
Use Arrow Up and Arrow Down to select a turn, Enter to jump to it, and Escape to return to the chat.
google Grounding with Google Search

"""

