# -*- coding: utf-8 -*-
"""suc_udocker2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpEUzgQjV5NqwnNdN2KdquHbV5LOMMw7

https://github.com/indigo-dc/udocker/releases
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# wget https://github.com/indigo-dc/udocker/releases/download/1.3.17/udocker-1.3.17.tar.gz
# tar zxvf udocker-1.3.17.tar.gz
# export PATH=`pwd`/udocker-1.3.17/udocker:$PATH

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# udocker --allow-root --help
# udocker --allow-root install

--allow-root

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# udocker --allow-root --help

"""https://github.com/indigo-dc/udocker/releases



### https://github.com/indigo-dc/udocker
"""

!udocker-1.3.17/udocker/udocker --allow-root -h

udocker setup --help

!udocker-1.3.17/udocker/udocker  --allow-root setup --help

